#!/bin/sh /etc/rc.common

START=99
STOP=99

USE_PROCD=1

start_service() {
  procd_open_instance
  procd_set_param command /overlay/rut_wialon_gateway/RWG_app_controller.sh
  procd_set_param stdout 1
  procd_set_param stderr 1
  procd_close_instance
}

stop_service() {
  pgrep -f "RWG" | xargs kill
}

reload_service() {
  pgrep -f "RWG" | xargs kill
  start_service
}

restart_service() {
  pgrep -f "RWG" | xargs kill
  start_service
}
