#!/bin/sh /etc/rc.common

START=99
STOP=99

USE_PROCD=1
PROG=/overlay/wialon_rut955_gateway/rut_wialon_gateway.sh


start_service() {
    procd_open_instance
    procd_set_param command /bin/sh -c "$PROG"
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

stop_service() {
    pgrep -f "rut_wialon_gateway" | xargs kill
}

reload_service() {
    pgrep -f "rut_wialon_gateway" | xargs kill
    start_service
}

restart_service() {
    pgrep -f "rut_wialon_gateway" | xargs kill
    start_service
}
